name: Build GDScript SDK and Release

on:
  push:
    branches:
      - 'main'


permissions:
  contents: write

env:
  GENERATE_LANGUAGE_CODE: zh_CN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: |
          sudo apt-get update
          sudo apt-get install zip unzip
          sudo apt-get install -y php-cli

      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: |
          git clone https://github.com/JetBrains/godot-support.git
          mv main.py godot-support/gdscript/php/translate.py
          mv requirements.txt godot-support/gdscript/php/requirements.txt
          cd godot-support/gdscript/php
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sed -i '/<?php/a\exec("python translate.py ${{ env.GENERATE_LANGUAGE_CODE }}");' classParser.php
          php sdkBuilder.php
          find ./sdk -type f ! -name "_gd-sdk-file-stamp.txt" | wc -l > ./sdk/_gd-sdk-file-stamp.txt
          cd sdk
          zip -r -9 ../gdscript_sdk.zip ./*

      - id: check_sdk
        run: |
          if [ -f godot-support/gdscript/php/gdscript_sdk.zip ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - if: steps.check_sdk.outputs.exists == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: sdk-${{ github.run_number }}-${{ github.sha }}
          release_name: GDScript SDK ${{ github.run_number }}
          draft: false
          prerelease: false

      - if: steps.check_sdk.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./godot-support/gdscript/php/gdscript_sdk.zip
          asset_name: gdscript_sdk.zip
          asset_content_type: application/zip